### ISSUE TITLE
recognizing square brackets

### ISSUE THREAD

**Issue by shcrela** [Alino/json-to-freemind#1]
Hi and thank you for the tool! I find it very helpful to be able to examine complex json files like a mind map.
However, in the json files I'm currently interested in, there are some fields which are in fact lists (square brackets are used to designate those). Your script just seems to ignore those, putting all the elements inside square brackuets on the same level. Would it be possible to add an intermediate level for each element inside square brackets. It could be 0:, 1:, 2: etc.
If my explanation is not clear, I can send you an example of the json file which illustrates the issue.

Cheers,
Dejan.

**Comment by dma61** [comment]
I suppose i have the same issue; Seems a great tool to get json's visualized. However i got errors

by the way, Installing on npm told me about a depreciation
=> npm WARN deprecated xmldom@0.1.31: Deprecated due to CVE-2021-21366 resolved in 0.5.0 <=

Running the script leads to errors:

F:\Downloads\Json2Freemind>json-to-freemind BatteryHistory.json myfile.mm
TypeError: Cannot read property 'appendChild' of undefined
    at value.forEach (C:\Users\user\AppData\Roaming\npm\node_modules\json-to-freemind\app.js:51:26)
    at Array.forEach (<anonymous>)
    at recur (C:\Users\user\AppData\Roaming\npm\node_modules\json-to-freemind\app.js:44:15)
    at convert (C:\Users\user\AppData\Roaming\npm\node_modules\json-to-freemind\app.js:84:4)
    at createMindMap (C:\Users\user\AppData\Roaming\npm\node_modules\json-to-freemind\app.js:10:23)
    at main (C:\Users\user\AppData\Roaming\npm\node_modules\json-to-freemind\cli.js:8:13)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\json-to-freemind\cli.js:15:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

I used this json sample file:

{"Batteries":[{"CTLabel":"6GUCLN7GWA7JEU","ChargeCapacity":[{"D":"20180301","C":"96"},{"D":"20180308","C":"97"},{"D":"20180315","C":"97"},{"D":"20180322","C":"95"},{"D":"20180330","C":"95"},{"D":"20180405","C":"96"},{"D":"20180412","C":"96"},{"D":"20180419","C":"94"},{"D":"20180426","C":"94"},{"D":"20180503","C":"94"},{"D":"20180518","C":"94"},{"D":"20180524","C":"94"},{"D":"20180531","C":"94"},{"D":"20180607","C":"94"},{"D":"20180615","C":"92"},{"D":"20180621","C":"92"},{"D":"20180628","C":"92"},{"D":"20180705","C":"92"},{"D":"20180712","C":"93"},{"D":"20180719","C":"92"},{"D":"20180726","C":"91"},{"D":"20180802","C":"92"},{"D":"20180820","C":"91"},{"D":"20180823","C":"92"},{"D":"20180830","C":"91"},{"D":"20180906","C":"91"},{"D":"20180914","C":"91"},{"D":"20180920","C":"94"},{"D":"20180927","C":"91"},{"D":"20181004","C":"92"},{"D":"20181011","C":"91"},{"D":"20181018","C":"92"},{"D":"20181025","C":"90"},{"D":"20181101","C":"91"},{"D":"20181108","C":"90"},{"D":"20181115","C":"92"},{"D":"20181122","C":"91"},{"D":"20181128","C":"90"},{"D":"20181130","C":"89"},{"D":"20181206","C":"91"},{"D":"20181213","C":"90"},{"D":"20181218","C":"91"},{"D":"20181228","C":"88"},{"D":"20190103","C":"89"},{"D":"20190110","C":"89"},{"D":"20190117","C":"89"},{"D":"20190124","C":"88"},{"D":"20190131","C":"90"},{"D":"20190207","C":"90"},{"D":"20190214","C":"90"},{"D":"20190221","C":"90"},{"D":"20190228","C":"89"},{"D":"20190307","C":"89"},{"D":"20190314","C":"87"},{"D":"20190329","C":"91"},{"D":"20190405","C":"91"},{"D":"20190411","C":"89"},{"D":"20190418","C":"90"},{"D":"20190425","C":"91"},{"D":"20190502","C":"91"},{"D":"20190510","C":"88"},{"D":"20190516","C":"88"},{"D":"20190524","C":"88"},{"D":"20190531","C":"87"},{"D":"20190607","C":"87"},{"D":"20190614","C":"88"},{"D":"20190621","C":"87"},{"D":"20190705","C":"88"},{"D":"20190711","C":"87"},{"D":"20190718","C":"88"},{"D":"20190725","C":"88"},{"D":"20190801","C":"88"},{"D":"20190809","C":"87"},{"D":"20190822","C":"87"},{"D":"20190823","C":"87"},{"D":"20190829","C":"88"},{"D":"20190901","C":"88"},{"D":"20190905","C":"87"},{"D":"20190913","C":"87"},{"D":"20190919","C":"86"},{"D":"20190926","C":"86"},{"D":"20191003","C":"85"},{"D":"20191010","C":"84"},{"D":"20191017","C":"85"},{"D":"20191024","C":"84"},{"D":"20191031","C":"87"},{"D":"20191107","C":"87"},{"D":"20191115","C":"86"},{"D":"20191120","C":"87"},{"D":"20191121","C":"86"},{"D":"20191127","C":"86"},{"D":"20191202","C":"84"},{"D":"20191205","C":"85"},{"D":"20191212","C":"86"},{"D":"20191219","C":"86"},{"D":"20191227","C":"84"},{"D":"20200102","C":"85"},{"D":"20200109","C":"84"},{"D":"20200116","C":"85"},{"D":"20200123","C":"86"},{"D":"20200130","C":"87"},{"D":"20200213","C":"85"},{"D":"20200220","C":"85"},{"D":"20200227","C":"86"},{"D":"20200305","C":"86"},{"D":"20200312","C":"86"},{"D":"20200319","C":"86"},{"D":"20200326","C":"85"},{"D":"20200402","C":"85"},{"D":"20200409","C":"83"},{"D":"20200416","C":"83"},{"D":"20200423","C":"84"},{"D":"20200430","C":"85"},{"D":"20200507","C":"81"},{"D":"20200514","C":"84"},{"D":"20200521","C":"86"},{"D":"20200528","C":"84"},{"D":"20200604","C":"84"},{"D":"20200611","C":"84"},{"D":"20200618","C":"84"},{"D":"20200625","C":"84"},{"D":"20200629","C":"83"},{"D":"20200702","C":"84"},{"D":"20200709","C":"84"},{"D":"20200723","C":"82"},{"D":"20200730","C":"82"},{"D":"20200803","C":"83"},{"D":"20200806","C":"83"},{"D":"20200813","C":"82"},{"D":"20200824","C":"83"},{"D":"20200828","C":"83"},{"D":"20200903","C":"83"},{"D":"20200910","C":"83"},{"D":"20200914","C":"83"},{"D":"20200917","C":"83"},{"D":"20200924","C":"80"},{"D":"20201002","C":"81"},{"D":"20201008","C":"82"},{"D":"20201015","C":"79"},{"D":"20201022","C":"78"},{"D":"20201029","C":"78"},{"D":"20201105","C":"82"},{"D":"20201116","C":"79"},{"D":"20201119","C":"81"},{"D":"20201120","C":"81"},{"D":"20201126","C":"82"},{"D":"20201203","C":"82"},{"D":"20201210","C":"82"},{"D":"20201217","C":"81"},{"D":"20201228","C":"81"},{"D":"20201231","C":"81"},{"D":"20210107","C":"82"},{"D":"20210114","C":"81"},{"D":"20210121","C":"80"},{"D":"20210128","C":"78"},{"D":"20210204","C":"79"},{"D":"20210211","C":"76"},{"D":"20210218","C":"80"},{"D":"20210225","C":"77"},{"D":"20210304","C":"76"},{"D":"20210311","C":"80"},{"D":"20210318","C":"80"},{"D":"20210321","C":"80"},{"D":"20210325","C":"80"},{"D":"20210401","C":"80"},{"D":"20210408","C":"78"},{"D":"20210415","C":"80"},{"D":"20210422","C":"80"},{"D":"20210429","C":"80"},{"D":"20210506","C":"80"},{"D":"20210514","C":"80"},{"D":"20210520","C":"80"},{"D":"20210527","C":"80"},{"D":"20210604","C":"80"}]}]}

Who / can will solve this?

**Comment by Alino** [comment]
Hi guys, thanks for reporting the issue. I was not using this tool at all. It was kind of a coding idea for me and was instantly abandoned. I was just bored now and looked at it after years. And was able to fix this issue. The issue happened when any of the top level key values in the json are array type.
